# clouddeploy.yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-manufacturing-pipeline
description: Cloud Manufacturing Pipeline
serialPipeline:
  stages:
  - targetId: test
    profiles: []
  - targetId: prod
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: Test environment
run:
  location: ueurope-west2
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production environment
run:
  location: europe-west2