steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        pip install -r requirements.txt
        pip install python-dotenv
        python test.py
    secretEnv: ['PROJECT_ID', 'SECRET_ID']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/project_id/versions/latest
    env: 'PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/secret_id/versions/latest
    env: 'SECRET_ID'

options:
  logging: CLOUD_LOGGING_ONLY