steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "PROJECT_ID: $PROJECT_ID"
        cd backend
        pip install -r requirements.txt
        pip install google-cloud-firestore google-cloud-secret-manager python-dotenv
        python test.py
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    secretEnv: ['FIRESTORE_SECRET']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/firestore-secret/versions/latest
    env: 'FIRESTORE_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY