steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Current directory:"
    pwd
    echo "Directory contents:"
    ls -la
    echo "Python version:"
    python --version

options:
  logging: CLOUD_LOGGING_ONLY