steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Access the secret
        echo "Accessing Firestore credentials..."
        gcloud secrets versions access latest --secret=firestore-secret > /tmp/firestore-credentials.json

        # Navigate to the backend directory
        cd backend

        # Install dependencies
        echo "Installing dependencies..."
        pip install -r requirements.txt

        # Run tests
        echo "Running tests..."
        python -m pytest test.py -v

# Set the timeout for the build (optional)
timeout: '1800s'

# Use Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY