steps:
- name: 'python:3.9'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Print the directory structure for debugging
    echo "Current directory structure:"
    ls -R
    # Ensure the backend directory exists
    if [ -d "backend" ]; then
      cd backend
    else
      echo "Backend directory not found."
      exit 1
    fi
    # Print the backend directory structure for debugging
    echo "Backend directory structure:"
    ls -R
    # Set up virtual environment
    python -m venv /tmp/venv
    . /tmp/venv/bin/activate
    # Install requirements
    if [ -f "requirements.txt" ]; then
      pip install -r requirements.txt
    else
      echo "requirements.txt not found."
      exit 1
    fi
    # Run tests
    if [ -f "test.py" ]; then
      pytest test.py
    else
      echo "Test file not found."
      exit 1
    fi

options:
  logging: CLOUD_LOGGING_ONLY
