steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PROJECT_ID="cloud-based-manufacturing"
        echo "PROJECT_ID: $PROJECT_ID"
        echo "All environment variables:"
        env
        cd backend
        pip install -r requirements.txt
        pip install python-dotenv google-cloud-secret-manager
        python -c "
        import os
        print('Python environment variables:')
        for key, value in os.environ.items():
            print(f'{key}: {value}')
        from google.cloud import secretmanager
        client = secretmanager.SecretManagerServiceClient()
        project_id = os.environ.get('PROJECT_ID')
        print(f'Attempting to access secrets for project: {project_id}')
        name = f'projects/{project_id}/secrets/project_id/versions/latest'
        try:
            response = client.access_secret_version(request={'name': name})
            print('Successfully accessed secret')
        except Exception as e:
            print(f'Error accessing secret: {e}')
        "
        python test.py
    secretEnv: ['SECRET_ID']

availableSecrets:
  secretManager:
  - versionName: projects/cloud-based-manufacturing/secrets/secret_id/versions/latest
    env: 'SECRET_ID'

options:
  logging: CLOUD_LOGGING_ONLY