steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PROJECT_ID="cloud-based-manufacturing"
        export SECRET_ID="firestore-secret"
        echo "PROJECT_ID: $PROJECT_ID"
        echo "SECRET_ID: $SECRET_ID"
        echo "All environment variables:"
        env
        cd backend
        pip install -r requirements.txt
        pip install python-dotenv google-cloud-secret-manager
        python test.py
    secretEnv: ['FIRESTORE_SECRET']

availableSecrets:
  secretManager:
  - versionName: projects/cloud-based-manufacturing/secrets/firestore-secret/versions/latest
    env: 'FIRESTORE_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY