steps:
- name: 'python:3.9'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    python -m venv /tmp/venv
    . /tmp/venv/bin/activate
    cd backend
    pip install -r requirements.txt
    pytest tests/

- name: 'python:3.9'
  entrypoint: python
  args: ['-m', 'pytest', 'tests/']

options:
  logging: CLOUD_LOGGING_ONLY
