steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret=firestore-credentials > /tmp/credentials.json
    python -m venv /tmp/venv
    . /tmp/venv/bin/activate
    cd backend
    pip install -r requirements.txt
    GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json pytest test.py

- name: 'python:3.9'
  entrypoint: python
  args: ['-m', 'pytest', 'backend/test.py']

options:
  logging: CLOUD_LOGGING_ONLY