steps:
  # Use the Cloud SDK image which includes both Python and gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Print Python version for verification
        python --version
        gcloud config set project cloud-based-manufacturing
        
        # Access the Firestore credentials from Secret Manager
         echo "Accessing Firestore credentials..."
        gcloud secrets versions access latest --secret=projects/970617304871/secrets/firestore-credentials > /tmp/firestore-credentials.json
        
        # Set the credentials for use in tests
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firestore-credentials.json
        
        # Navigate to the backend directory
        cd backend
        
        # Install dependencies
        echo "Installing dependencies..."
        pip install -r requirements.txt
        
        # Run tests
        echo "Running tests..."
        python -m pytest test.py

# Set the timeout for the build (optional)
timeout: '1800s'

# Use Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY